version: "3.7"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,sqs
      #   - DATA_DIR=/tmp/localstack/data (for persistence)
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
